name: Repo Sync to Gitee
on:
  # 每次手动push后
  push:
    branches:
      - main
      - master

  # 在 Excavator 完成后
  workflow_run:
    workflows: [Excavator]
    types:
      - completed
env:
  # 仓库名称
  REPO_NAME: ${{ github.event.repository.name }}
  # Gitee 用户名
  USER_NAME: morning-start

jobs:
  mirror-to-gitee:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && github.event.pusher.name != 'github-actions[bot]') ||
      (github.event_name == 'workflow_run')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check and create Gitee repository if needed
        run: |
          echo "检查 Gitee 仓库: ${{ env.USER_NAME }}/${{ env.REPO_NAME }}"

          # 检查 Gitee 仓库是否存在
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://gitee.com/api/v5/repos/${{ env.USER_NAME }}/${{ env.REPO_NAME }}?access_token=${{ secrets.GITEE_TOKEN }}")

          echo "API 响应状态码: $response"

          if [ "$response" = "404" ]; then
            echo "仓库不存在，正在创建新仓库..."

            # 创建新仓库
            create_response=$(curl -s -X POST "https://gitee.com/api/v5/user/repos" \
              -H "Content-Type: application/json" \
              -d "{
                \"access_token\": \"${{ secrets.GITEE_TOKEN }}\",
                \"name\": \"${{ env.REPO_NAME }}\",
                \"description\": \"Auto-synced from GitHub repository ${{ github.repository }}\",
                \"private\": false,
                \"has_issues\": true,
                \"has_wiki\": true,
                \"can_comment\": true
              }")

            echo "创建仓库响应: $create_response"
            echo "✅ 仓库创建完成，准备同步..."
          elif [ "$response" = "200" ]; then
            echo "✅ 仓库已存在，直接进行同步..."
          else
            echo "❌ 检查仓库时出现异常，状态码: $response"
            exit 1
          fi
        shell: bash

      - name: Sync to Gitee
        run: |
          echo "开始同步到 Gitee..."

          # 配置 Git 用户信息
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # 添加 Gitee 远程仓库
          git remote add gitee https://${{ env.USER_NAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ env.USER_NAME }}/${{ env.REPO_NAME }}.git || \
          git remote set-url gitee https://${{ env.USER_NAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ env.USER_NAME }}/${{ env.REPO_NAME }}.git

          # 推送所有分支和标签
          git push gitee --all --force
          git push gitee --tags --force

          echo "✅ 同步完成"
        shell: bash
